name: CI-CD
on:
  push:
    branches:
      - master
  pull_request:
        branches:
        - master
jobs:
 build:
  name: Build and Push
  runs-on: ubuntu-latest
  outputs: 
    docker_tag: ${{steps.generate_tag.outputs.sha}}

  steps:
  - name: Checkout source code
    uses: actions/checkout@v4

  - name: Setup Nodejs
    uses: actions/setup-node@v4
    with:
      node-version: '22'
  
  - name: Setup Corepack
    run: corepack enable

  - name: Install dependencies
    run: yarn

  - name: Run tests
    run: yarn test

  - name: Generate Tag
    id: generate_tag
    run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

  - name: Login in DockerHub
    uses: docker/login-action@v3
    with:
      username: ${{secrets.DOCKERHUB_USERNAME}}
      password: ${{secrets.DOCKERHUB_TOKEN}}

  - name: Build Docker Image
    run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/aula-devops-2025-2:${{steps.generate_tag.outputs.sha}}

  - name: Push to Docker Hub
    run: docker push ${{secrets.DOCKERHUB_USERNAME}}/aula-devops-2025-2:${{steps.generate_tag.outputs.sha}}
